- .github/actions/package-json/README.md
- .github/actions/package-json/action.yml
- .github/actions/package-json/dist/index.js
- .github/actions/package-json/index.ts
> Add version parameter to the GitHub action `package.json` with dots replaced by dashes

- .github/workflows/workflow.yml
> ci: trigger build on push or pull request

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v10.0.0-beta.1

- apps/toolkit-testing-app/src/app/app-routing.module.ts
- apps/toolkit-testing-app/src/app/sci-accordion-page/sci-accordion-page.component.html
- apps/toolkit-testing-app/src/app/sci-checkbox-page/sci-checkbox-page.component.html
- apps/toolkit-testing-app/src/app/sci-filter-field-page/sci-filter-field-page.component.html
- apps/toolkit-testing-app/src/app/sci-form-field-page/sci-form-field-page.component.html
- apps/toolkit-testing-app/src/app/sci-list-page/sci-list-page.component.html
- apps/toolkit-testing-app/src/app/sci-params-enter-page/sci-params-enter-page.component.html
- apps/toolkit-testing-app/src/app/sci-property-page/sci-property-page.component.html
- apps/toolkit-testing-app/src/app/sci-qualifier-chip-list-page/sci-qualifier-chip-list-page.component.html
- apps/toolkit-testing-app/src/app/sci-tabbar-page/sci-tabbar-page.component.html
- apps/toolkit-testing-app/src/app/sci-tabbar-page/sci-tabbar-page.component.scss
- apps/toolkit-testing-app/src/app/sci-tabbar-page/sci-tabbar-page.component.ts
- apps/toolkit-testing-app/src/app/sci-tabbar-page/sci-tabbar-page.module.ts
- apps/toolkit-testing-app/src/app/sci-tabbar-page/split.pipe.ts
- projects/scion/toolkit.internal/widgets/src/public_api.ts
- projects/scion/toolkit.internal/widgets/src/tabbar/public_api.ts
- projects/scion/toolkit.internal/widgets/src/tabbar/tab.directive.ts
- projects/scion/toolkit.internal/widgets/src/tabbar/tabbar.component.html
- projects/scion/toolkit.internal/widgets/src/tabbar/tabbar.component.scss
- projects/scion/toolkit.internal/widgets/src/tabbar/tabbar.component.ts
- projects/scion/toolkit.internal/widgets/src/tabbar/tabbar.module.ts
> feat(ɵtoolkit): allow organizing content in tabs

- apps/toolkit-testing-app/src/app/sci-list-page/sci-list-page.component.ts
- tslint.json
> fix(toolkit): fix faulty tslint and remove arrow-call-signature

- projects/scion/toolkit.internal/package.json
> chore(ɵtoolkit): add @scion/toolkit as peer dependency

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v10.0.0-beta.2

- projects/scion/toolkit/testing/src/observe-captor.spec.ts
- projects/scion/toolkit/testing/src/observe-captor.ts
- projects/scion/toolkit/testing/src/public_api.ts
> fix(toolkit/testing): capture error in `ObserveCaptor`

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
Please refer to the changelog which you find [here](https://github.com/SchweizerischeBundesbahnen/scion-toolkit/blob/master/docs/site/changelog/changelog.md).
> release: v11.0.0-beta.1

- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> fix(toolkit): restrict the toolkit to be compatible with Angular version 11

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v11.0.0-beta.2

- .github/actions/tag-release-commit/README.md
- .github/actions/tag-release-commit/action.yml
- .github/actions/tag-release-commit/dist/index.js
- .github/actions/tag-release-commit/index.ts
- package.json
> ci: allow to set a custom Git release tag in GitHub action

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
* **toolkit/viewport:** Renamed CSS variables to lay out viewport content.
To migrate: If customizing the default layout of viewport content, replace the following CSS variables:
- `--grid-template-columns` -> `--sci-viewport-content-grid-template-columns`
- `--grid-template-rows` -> `--sci-viewport-content-grid-template-rows`
- `--grid-auto-columns` -> `--sci-viewport-content-grid-auto-columns`
- `--grid-auto-rows` -> `--sci-viewport-content-grid-auto-rows`
- `--gap` -> `--sci-viewport-content-grid-gap`
> release: v11.0.0-beta.3

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v11.0.0-beta.4

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
See https://github.com/SchweizerischeBundesbahnen/scion-toolkit/blob/master/docs/site/changelog/changelog.md#1100-beta5-2021-01-11.
> release: v11.0.0-beta.5

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v11.0.0-beta.6

- projects/scion/toolkit/util/src/dictionaries.util.spec.ts
- projects/scion/toolkit/util/src/dictionaries.util.ts
- projects/scion/toolkit/util/src/maps.util.spec.ts
- projects/scion/toolkit/util/src/maps.util.ts
> feat(toolkit/util): support the coercion of Map's from other JavaScript realms

- .github/workflows/workflow.yml
- CONTRIBUTING.md
- docs/site/tools/sashbox.md
- docs/site/tools/throbber.md
- docs/site/tools/viewport.md
- projects/scion/toolkit.internal/widgets/src/accordion/accordion.component.ts
- projects/scion/toolkit.internal/widgets/src/list/list.component.html
- projects/scion/toolkit.internal/widgets/src/list/list.component.scss
> chore: migrate vercel deployments to the updated url format

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v11.0.0-beta.9

- projects/scion/toolkit/storage/src/web-storage.spec.ts
- projects/scion/toolkit/testing/src/observe-captor.spec.ts
- projects/scion/toolkit/testing/src/observe-captor.ts
> fix(toolkit/testing): allow to reset the emit count of `ObserveCaptor`

- docs/site/tools/throbber.md
- projects/scion/toolkit/bean-manager/src/bean-manager.ts
- projects/scion/toolkit/dimension/src/dimension.directive.ts
- projects/scion/toolkit/observable/src/bounding-client-rect.observable.ts
- projects/scion/toolkit/observable/src/dimension.observable.ts
- projects/scion/toolkit/operators/src/operators.ts
- projects/scion/toolkit/sashbox/src/sash-initializer.directive.ts
- projects/scion/toolkit/sashbox/src/sash.directive.ts
- projects/scion/toolkit/sashbox/src/splitter.directive.ts
- projects/scion/toolkit/storage/src/web-storage.ts
- projects/scion/toolkit/throbber/src/ripple-throbber/ripple-throbber.component.ts
- projects/scion/toolkit/throbber/src/throbber.component.ts
- projects/scion/toolkit/tsconfig.lib.json
- projects/scion/toolkit/tslint.json
- projects/scion/toolkit/util/src/arrays.util.ts
- projects/scion/toolkit/util/src/defined.util.ts
- projects/scion/toolkit/util/src/dictionaries.util.ts
- projects/scion/toolkit/util/src/maps.util.ts
- projects/scion/toolkit/viewport/src/native-scrollbar-track-size-provider.service.ts
- projects/scion/toolkit/viewport/src/scrollable.directive.ts
- projects/scion/toolkit/viewport/src/scrollbar/scrollbar.component.ts
- projects/scion/toolkit/viewport/src/viewport.component.ts
> chore(toolkit): compile with TypeScript strict checks enabled

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v11.0.0-beta.11

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v11.0.0-beta.12

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v12.0.0-beta.1

- package-lock.json
- package.json
> chore(toolkit): remove unused dependency

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v12.0.0-beta.2

- .eslintrc.json
- package-lock.json
- package.json
- projects/scion/toolkit.internal/widgets/src/list/list.component.ts
> chore: add eslint deprecation plugin

- .npmrc
- package-lock.json
> chore: use tls for connecting to npm registry

- CHANGELOG.md
- README.md
- docs/site/changelog/changelog.md
- docs/site/projects-overview.md
- projects/scion/toolkit/README.md
> docs: correct incorrect usages of the word "agnostic"

- CHANGELOG.md
- docs/site/changelog/changelog.md
- package-lock.json
- package.json
- projects/scion/toolkit.internal/package.json
- projects/scion/toolkit/package.json
> release: v13.0.0-beta.2

- CHANGELOG_COMPONENTS.md
- docs/site/changelog-components/changelog.md
- projects/scion/components/package.json
> release(components): v14.0.1

- projects/scion/components/viewport/src/viewport.component.spec.ts
- projects/scion/toolkit/bean-manager/src/bean-manager.spec.ts
- projects/scion/toolkit/bean-manager/src/bean-manager.ts
- projects/scion/toolkit/testing/src/observe-captor.spec.ts
- projects/scion/toolkit/util/src/arrays.util.spec.ts
- projects/scion/toolkit/util/src/objects.util.spec.ts
> fix(toolkit/bean-manager): do not destroy "value beans"

- projects/scion/toolkit/util/src/arrays.util.spec.ts
- projects/scion/toolkit/util/src/arrays.util.ts
> fix(toolkit/util): fix comparing unordered arrays

- apps/components-testing-app/src/app/sci-viewport/hover/viewport-hover-page.component.html
- apps/components-testing-app/src/app/sci-viewport/hover/viewport-hover-page.component.scss
- apps/components-testing-app/src/app/sci-viewport/hover/viewport-hover-page.component.ts
- apps/components-testing-app/src/app/sci-viewport/index.ts
- projects/scion/components.e2e/playwright.config.ts
- projects/scion/components.e2e/src/helper/testing.utils.ts
- projects/scion/components.e2e/src/sci-viewport/focus/viewport-focus-page.po.ts
- projects/scion/components.e2e/src/sci-viewport/focus/viewport-focus.e2e-spec.ts
- projects/scion/components.e2e/src/sci-viewport/hover/viewport-hover-page.po.ts
- projects/scion/components.e2e/src/sci-viewport/hover/viewport-hover.e2e-spec.ts
- projects/scion/components.e2e/src/sci-viewport/overlap/viewport-overlap-page.po.ts
- projects/scion/components.e2e/src/sci-viewport/overlap/viewport-overlap.e2e-spec.ts
- projects/scion/components/viewport/_scrollbar.scss
- projects/scion/components/viewport/src/viewport.component.html
> fix(components/viewport): display scrollbar only when hovering the viewport

- projects/scion/components.internal/accordion/src/accordion.component.scss
> fix(ɵcomponents): fix accordion content width to fill entire space

- package.json
- projects/scion/components.e2e/playwright.config.ts
- projects/scion/components.e2e/tsconfig.json
> chore: enable TypeScript strict mode in end-to-end tests

- docs/site/scion-design-tokens.md
- projects/scion/components/_index.scss
> docs(components): improve documentation of design tokens

- projects/scion/components/_scrollbar.scss
- tsconfig.json
> chore: remove `downlevelIteration` from tsconfig

- .github/workflows/workflow.yml
> ci(components-app): revert removal of versioned Vercel URL alias

- docs/site/scion-components.md
- docs/site/tools/dimension.md
- docs/site/tools/observable.md
- projects/scion/components/README.md
- projects/scion/components/dimension/src/bounding-client-rect.signal.spec.ts
- projects/scion/components/dimension/src/bounding-client-rect.signal.ts
- projects/scion/components/dimension/src/dimension.directive.spec.ts
- projects/scion/components/dimension/src/dimension.directive.ts
- projects/scion/components/dimension/src/dimension.signal.spec.ts
- projects/scion/components/dimension/src/dimension.signal.ts
- projects/scion/components/dimension/src/dimension.ts
- projects/scion/components/dimension/src/public_api.ts
- projects/scion/toolkit/observable/src/bounding-client-rect.observable.spec.ts
- projects/scion/toolkit/observable/src/bounding-client-rect.observable.ts
- projects/scion/toolkit/operators/src/operators.spec.ts
> Issue/from bounding client rect$

- CHANGELOG_COMPONENTS.md
- CHANGELOG_COMPONENTS_LATEST.md
- docs/site/changelog-components/changelog.md
> release(components): v19.0.0

- CHANGELOG_COMPONENTS_INTERNAL.md
- docs/site/changelog-components.internal/changelog.md
> release(ɵcomponents): v19.0.0

- angular.json
> fix(components-testing-app): add favicon

- .github/workflows/workflow.yml
- projects/scion/components.e2e/playwright.config.ts
> ci: upload Playwright video on failure
